version: "3.9"
networks:
  brilhador:
    driver: bridge
services:
  postgres-brilhador:
    container_name: postgres-brilhador
    image: postgres
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "brilhador"
    ports:
      - "5432:5432"
    volumes:
      - .:/app
    working_dir: /app
    networks:
      - brilhador
  rabbitmq:
    container_name: rabbitmq-server
    image: rabbitmq:3.9-management
    environment:
      RABBITMQ_CONFIG_FILE: ./rabbitmq.conf
    ports:
      - "5673:5673"
      - "15672:15672"
    volumes:
      - .:/app
    working_dir: /app
    networks:
      - brilhador
  api-gateway:
    container_name: brilhador-api-gateway
    image: openjdk:17.0.2-slim-buster
    working_dir: /app
    ports:
      - "4000:8080"
    volumes:
      - ./api-gateway:/app
    command: ./mvnw spring-boot:run -X
    networks:
      - brilhador
  authentication-service-brilhador:
    container_name: authentication-service-brilhador
    image: openjdk:17.0.2-slim-buster
    volumes:
      - ./authentication:/app
    working_dir: /app
    expose:
      - 80
    command: ./mvnw spring-boot:run -X
    networks:
      - brilhador
  client-relationship-service-brilhador:
    container_name: client-relationship-service-brilhador
    image: openjdk:17.0.2-slim-buster
    volumes:
      - ./client-relationship:/app
    working_dir: /app
    expose:
      - 80
    command: ./mvnw spring-boot:run -X
    networks:
      - brilhador
  mail-service-brilhador:
    container_name: mail-services-brilhador
    image: openjdk:17.0.2-slim-buster
    volumes:
      - ./mail:/app
    working_dir: /app
    expose:
      - 80
    command: ./mvnw spring-boot:run -X
    networks:
      - brilhador
  strategic-systems-service-brilhador:
    container_name: strategic-systems-services-brilhador
    image: openjdk:17.0.2-slim-buster
    volumes:
      - ./strategic-systems-project:/app
    working_dir: /app
    expose:
      - 80
    command: ./mvnw spring-boot:run -X
    networks:
      - brilhador
  financial-lancamentos-contabeis-brilhador:
    container_name: financial-lancamentos-contabeis-brilhador
    image: openjdk:11.0.15-slim-buster
    volumes:
      - './financial/lancamentos_contabeis:/app'
    working_dir: /app
    expose:
      - 80
    command: sh mvnw spring-boot:run -X
    networks:
      - brilhador
  financial-operacaocontabil-brilhador:
    container_name: financial-operacaocontabil-brilhador
    image: openjdk:18.0.1.1-slim-buster
    volumes:
      - './financial/operacaocontabil:/app'
    working_dir: /app
    expose:
      - 80
    command: sh mvnw spring-boot:run -X
    networks:
      - brilhador
  financial-patrimonial-brilhador:
    container_name: financial-patrimonial-brilhador
    image: openjdk:18.0.1.1-slim-buster
    volumes:
      - './financial/patrimonial:/app'
    working_dir: /app
    expose:
      - 80
    command: sh mvnw spring-boot:run -X
    networks:
      - brilhador
  financial-plano-contas-brilhador:
    container_name: financial-plano-contas-brilhador
    image: openjdk:11.0.15-slim-buster
    volumes:
      - './financial/plano-contas:/app'
    working_dir: /app
    expose:
      - 80
    command: sh mvnw spring-boot:run -X
    networks:
      - brilhador
